{% set name = "coiled" %}
{% set version = "0.0.63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d1c26f642ab512e7bd2de32ebc393795be4536758d0a2c7d3e2c80d73e94940

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7, <3.10
    - pip
    - wheel
    - pbr
    - versioneer-518
  run:
    - python >=3.7, <3.10
    - aiohttp
    - aiobotocore >=1.1.1
    - backoff >=1.10.0
    - boto3
    - click >=7.1
    - dask >=2.23.0
    - s3fs
    - pandas >=1.1.0
    - ipython
    - rich >=9.4.0
    - typing-extensions

test:
  requires:
    - pip
  commands:
    - pip check
    - coiled install --help
    - coiled login --help
    - coiled env --help
    - coiled --version
  imports:
    - coiled

about:
  home: https://coiled.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deploy Dask cluster using Coiled Cloud

  description: |
    A Python package to easily create, manage, and connect to Dask deployments
    using Coiled Cloud.
  doc_url: https://coiled.io/cloud

extra:
  recipe-maintainers:
    - dchudz
    - matthiasdv
    - jrbourbeau
    - mrocklin
    - ian-r-rose
    - necaris
