{% set name = "coiled" %}
{% set version = "0.9.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87f2c7512307230490e9171bacf48d89c0baf222b9e4ff41255341c1e19f43fd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - coiled = coiled.cli.core:cli

requirements:
  host:
    - python >=3.8
    - pip
    - wheel
    - hatchling
    - hatch-vcs
  run:
    - python >=3.7
    - aiohttp
    - backoff
    - boto3
    - click >=7.1
    - dask >=2.23.0
    - distributed >=2.23.0
    - filelock
    - gilknocker >=0.4.1
    - importlib-metadata
    - ipywidgets
    - jmespath
    - jsondiff
    - pip >=19.3
    - prometheus_client
    - rich >=11.2.0
    - toml
    - setuptools >=49.3.0
    - typing-extensions
    - wheel

test:
  requires:
    - pip
  commands:
    - pip check
    - coiled login --help
    - coiled env --help
    - coiled --version
  imports:
    - coiled

about:
  home: https://coiled.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deploy Dask cluster using Coiled Cloud

  description: |
    A Python package to easily create, manage, and connect to Dask deployments
    using Coiled Cloud.
  doc_url: https://coiled.io/cloud

extra:
  recipe-maintainers:
    - dan-blanchard
    - ntabris
    - shughes-uk
    - dchudz
    - jrbourbeau
    - mrocklin
