{% set name = "coiled" %}
{% set version = "0.2.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a18c3e716888307523aeb0c0b1c5bbf4debc8484c65ebe1e5534b4bcfe725051

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - coiled = coiled.cli.core:cli

requirements:
  host:
    - python >=3.7
    - pip
    - wheel
    - pbr
    - versioneer-518
  run:
    - python >=3.7
    - aiohttp
    - aiobotocore >=1.1.1
    - backoff >=1.10.0,<2.0.0
    - boto3
    - click >=7.1
    - dask >=2.23.0
    - s3fs
    - pandas >=1.1.0
    - ipython
    - ipywidgets >=7.0,<8.0
    - rich >=11.2.0
    - typing-extensions
    - jmespath
    - jinja2
    - textual
    - jsondiff
    - importlib-metadata

test:
  requires:
    - pip
  commands:
    - pip check
    - coiled install --help
    - coiled login --help
    - coiled env --help
    - coiled --version
  imports:
    - coiled

about:
  home: https://coiled.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deploy Dask cluster using Coiled Cloud

  description: |
    A Python package to easily create, manage, and connect to Dask deployments
    using Coiled Cloud.
  doc_url: https://coiled.io/cloud

extra:
  recipe-maintainers:
    - ntabris
    - shughes-uk
    - dchudz
    - jrbourbeau
    - mrocklin
    - ian-r-rose
