{% set name = "coiled" %}
{% set version = "1.133.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/a5/6c/89e4b61b4bf1b93457cb493ceb437e13c51a4e99edc2613c5dbd56822c81/coiled-{{ version }}.tar.gz
  sha256: 040963f84c4e42dc2880a0b925a2460a812cd654a422b55104004496a5d27357

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - coiled = coiled.cli.core:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - wheel
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - aiohttp
    - backoff
    - boto3
    - click >=7.1
    - dask >=2022.02.0
    - distributed >=2022.02.0
    - fabric >=3.0
    - filelock
    - gilknocker >=0.4.1
    - httpx >=0.15
    - importlib-metadata
    - invoke >=2.0
    - ipywidgets
    - jmespath
    - jsondiff
    - paramiko >=2.4
    - pip-requirements-parser
    - pip >=19.3
    - prometheus_client
    - rich >=11.2.0
    - toml
    - setuptools >=49.3.0
    - typing-extensions
    - wheel

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - coiled login --help
    - coiled env --help
    - coiled --version
  imports:
    - coiled

about:
  home: https://coiled.io
  license: Elastic-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Deploy Dask cluster using Coiled Cloud

  description: |
    A Python package to easily create, manage, and connect to Dask deployments
    using Coiled Cloud.
  doc_url: https://coiled.io/cloud

extra:
  recipe-maintainers:
    - ntabris
    - dchudz
    - jrbourbeau
    - mrocklin
